//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace EDIManagement.rptsource {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("PRODUCTIONPARTLABEL")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class PRODUCTIONPARTLABEL : global::System.Data.DataSet {
        
        private PRODUCTIONPARTLABELDataTable tablePRODUCTIONPARTLABEL;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public PRODUCTIONPARTLABEL() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected PRODUCTIONPARTLABEL(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["PRODUCTIONPARTLABEL"] != null)) {
                    base.Tables.Add(new PRODUCTIONPARTLABELDataTable(ds.Tables["PRODUCTIONPARTLABEL"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public PRODUCTIONPARTLABELDataTable _PRODUCTIONPARTLABEL {
            get {
                return this.tablePRODUCTIONPARTLABEL;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            PRODUCTIONPARTLABEL cln = ((PRODUCTIONPARTLABEL)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["PRODUCTIONPARTLABEL"] != null)) {
                    base.Tables.Add(new PRODUCTIONPARTLABELDataTable(ds.Tables["PRODUCTIONPARTLABEL"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tablePRODUCTIONPARTLABEL = ((PRODUCTIONPARTLABELDataTable)(base.Tables["PRODUCTIONPARTLABEL"]));
            if ((initTable == true)) {
                if ((this.tablePRODUCTIONPARTLABEL != null)) {
                    this.tablePRODUCTIONPARTLABEL.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "PRODUCTIONPARTLABEL";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/PRODUCTIONPARTLABEL.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablePRODUCTIONPARTLABEL = new PRODUCTIONPARTLABELDataTable();
            base.Tables.Add(this.tablePRODUCTIONPARTLABEL);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerialize_PRODUCTIONPARTLABEL() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            PRODUCTIONPARTLABEL ds = new PRODUCTIONPARTLABEL();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void PRODUCTIONPARTLABELRowChangeEventHandler(object sender, PRODUCTIONPARTLABELRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class PRODUCTIONPARTLABELDataTable : global::System.Data.TypedTableBase<PRODUCTIONPARTLABELRow> {
            
            private global::System.Data.DataColumn columnpplid;
            
            private global::System.Data.DataColumn columnpplpartnumber;
            
            private global::System.Data.DataColumn columnppldonumber;
            
            private global::System.Data.DataColumn columnpplpartname;
            
            private global::System.Data.DataColumn columnpplsupplieruse;
            
            private global::System.Data.DataColumn columnpplecsnumber;
            
            private global::System.Data.DataColumn columnpplquantity;
            
            private global::System.Data.DataColumn columnppllinedeliverycicle;
            
            private global::System.Data.DataColumn columnpplkanban;
            
            private global::System.Data.DataColumn columnpplwhloc;
            
            private global::System.Data.DataColumn columnppldeliverycicle;
            
            private global::System.Data.DataColumn columnpplordercode;
            
            private global::System.Data.DataColumn columnpplshipdate;
            
            private global::System.Data.DataColumn columnpplfitloc;
            
            private global::System.Data.DataColumn columnbcode;
            
            private global::System.Data.DataColumn columnbcode1;
            
            private global::System.Data.DataColumn columnbcode2;
            
            private global::System.Data.DataColumn columnbcode3;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public PRODUCTIONPARTLABELDataTable() {
                this.TableName = "PRODUCTIONPARTLABEL";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal PRODUCTIONPARTLABELDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected PRODUCTIONPARTLABELDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplidColumn {
                get {
                    return this.columnpplid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplpartnumberColumn {
                get {
                    return this.columnpplpartnumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ppldonumberColumn {
                get {
                    return this.columnppldonumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplpartnameColumn {
                get {
                    return this.columnpplpartname;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplsupplieruseColumn {
                get {
                    return this.columnpplsupplieruse;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplecsnumberColumn {
                get {
                    return this.columnpplecsnumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplquantityColumn {
                get {
                    return this.columnpplquantity;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ppllinedeliverycicleColumn {
                get {
                    return this.columnppllinedeliverycicle;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplkanbanColumn {
                get {
                    return this.columnpplkanban;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplwhlocColumn {
                get {
                    return this.columnpplwhloc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ppldeliverycicleColumn {
                get {
                    return this.columnppldeliverycicle;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplordercodeColumn {
                get {
                    return this.columnpplordercode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplshipdateColumn {
                get {
                    return this.columnpplshipdate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn pplfitlocColumn {
                get {
                    return this.columnpplfitloc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn bcodeColumn {
                get {
                    return this.columnbcode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn bcode1Column {
                get {
                    return this.columnbcode1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn bcode2Column {
                get {
                    return this.columnbcode2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn bcode3Column {
                get {
                    return this.columnbcode3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public PRODUCTIONPARTLABELRow this[int index] {
                get {
                    return ((PRODUCTIONPARTLABELRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event PRODUCTIONPARTLABELRowChangeEventHandler PRODUCTIONPARTLABELRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event PRODUCTIONPARTLABELRowChangeEventHandler PRODUCTIONPARTLABELRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event PRODUCTIONPARTLABELRowChangeEventHandler PRODUCTIONPARTLABELRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event PRODUCTIONPARTLABELRowChangeEventHandler PRODUCTIONPARTLABELRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddPRODUCTIONPARTLABELRow(PRODUCTIONPARTLABELRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public PRODUCTIONPARTLABELRow AddPRODUCTIONPARTLABELRow(
                        int pplid, 
                        string pplpartnumber, 
                        string ppldonumber, 
                        string pplpartname, 
                        string pplsupplieruse, 
                        string pplecsnumber, 
                        string pplquantity, 
                        string ppllinedeliverycicle, 
                        string pplkanban, 
                        string pplwhloc, 
                        string ppldeliverycicle, 
                        string pplordercode, 
                        string pplshipdate, 
                        string pplfitloc, 
                        byte[] bcode, 
                        byte[] bcode1, 
                        byte[] bcode2, 
                        byte[] bcode3) {
                PRODUCTIONPARTLABELRow rowPRODUCTIONPARTLABELRow = ((PRODUCTIONPARTLABELRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        pplid,
                        pplpartnumber,
                        ppldonumber,
                        pplpartname,
                        pplsupplieruse,
                        pplecsnumber,
                        pplquantity,
                        ppllinedeliverycicle,
                        pplkanban,
                        pplwhloc,
                        ppldeliverycicle,
                        pplordercode,
                        pplshipdate,
                        pplfitloc,
                        bcode,
                        bcode1,
                        bcode2,
                        bcode3};
                rowPRODUCTIONPARTLABELRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowPRODUCTIONPARTLABELRow);
                return rowPRODUCTIONPARTLABELRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                PRODUCTIONPARTLABELDataTable cln = ((PRODUCTIONPARTLABELDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new PRODUCTIONPARTLABELDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnpplid = base.Columns["pplid"];
                this.columnpplpartnumber = base.Columns["pplpartnumber"];
                this.columnppldonumber = base.Columns["ppldonumber"];
                this.columnpplpartname = base.Columns["pplpartname"];
                this.columnpplsupplieruse = base.Columns["pplsupplieruse"];
                this.columnpplecsnumber = base.Columns["pplecsnumber"];
                this.columnpplquantity = base.Columns["pplquantity"];
                this.columnppllinedeliverycicle = base.Columns["ppllinedeliverycicle"];
                this.columnpplkanban = base.Columns["pplkanban"];
                this.columnpplwhloc = base.Columns["pplwhloc"];
                this.columnppldeliverycicle = base.Columns["ppldeliverycicle"];
                this.columnpplordercode = base.Columns["pplordercode"];
                this.columnpplshipdate = base.Columns["pplshipdate"];
                this.columnpplfitloc = base.Columns["pplfitloc"];
                this.columnbcode = base.Columns["bcode"];
                this.columnbcode1 = base.Columns["bcode1"];
                this.columnbcode2 = base.Columns["bcode2"];
                this.columnbcode3 = base.Columns["bcode3"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnpplid = new global::System.Data.DataColumn("pplid", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplid);
                this.columnpplpartnumber = new global::System.Data.DataColumn("pplpartnumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplpartnumber);
                this.columnppldonumber = new global::System.Data.DataColumn("ppldonumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnppldonumber);
                this.columnpplpartname = new global::System.Data.DataColumn("pplpartname", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplpartname);
                this.columnpplsupplieruse = new global::System.Data.DataColumn("pplsupplieruse", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplsupplieruse);
                this.columnpplecsnumber = new global::System.Data.DataColumn("pplecsnumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplecsnumber);
                this.columnpplquantity = new global::System.Data.DataColumn("pplquantity", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplquantity);
                this.columnppllinedeliverycicle = new global::System.Data.DataColumn("ppllinedeliverycicle", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnppllinedeliverycicle);
                this.columnpplkanban = new global::System.Data.DataColumn("pplkanban", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplkanban);
                this.columnpplwhloc = new global::System.Data.DataColumn("pplwhloc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplwhloc);
                this.columnppldeliverycicle = new global::System.Data.DataColumn("ppldeliverycicle", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnppldeliverycicle);
                this.columnpplordercode = new global::System.Data.DataColumn("pplordercode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplordercode);
                this.columnpplshipdate = new global::System.Data.DataColumn("pplshipdate", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplshipdate);
                this.columnpplfitloc = new global::System.Data.DataColumn("pplfitloc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpplfitloc);
                this.columnbcode = new global::System.Data.DataColumn("bcode", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbcode);
                this.columnbcode1 = new global::System.Data.DataColumn("bcode1", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbcode1);
                this.columnbcode2 = new global::System.Data.DataColumn("bcode2", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbcode2);
                this.columnbcode3 = new global::System.Data.DataColumn("bcode3", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbcode3);
                this.ExtendedProperties.Add("Generator_TablePropName", "_PRODUCTIONPARTLABEL");
                this.ExtendedProperties.Add("Generator_UserTableName", "PRODUCTIONPARTLABEL");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public PRODUCTIONPARTLABELRow NewPRODUCTIONPARTLABELRow() {
                return ((PRODUCTIONPARTLABELRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new PRODUCTIONPARTLABELRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(PRODUCTIONPARTLABELRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.PRODUCTIONPARTLABELRowChanged != null)) {
                    this.PRODUCTIONPARTLABELRowChanged(this, new PRODUCTIONPARTLABELRowChangeEvent(((PRODUCTIONPARTLABELRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.PRODUCTIONPARTLABELRowChanging != null)) {
                    this.PRODUCTIONPARTLABELRowChanging(this, new PRODUCTIONPARTLABELRowChangeEvent(((PRODUCTIONPARTLABELRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.PRODUCTIONPARTLABELRowDeleted != null)) {
                    this.PRODUCTIONPARTLABELRowDeleted(this, new PRODUCTIONPARTLABELRowChangeEvent(((PRODUCTIONPARTLABELRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.PRODUCTIONPARTLABELRowDeleting != null)) {
                    this.PRODUCTIONPARTLABELRowDeleting(this, new PRODUCTIONPARTLABELRowChangeEvent(((PRODUCTIONPARTLABELRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovePRODUCTIONPARTLABELRow(PRODUCTIONPARTLABELRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                PRODUCTIONPARTLABEL ds = new PRODUCTIONPARTLABEL();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "PRODUCTIONPARTLABELDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class PRODUCTIONPARTLABELRow : global::System.Data.DataRow {
            
            private PRODUCTIONPARTLABELDataTable tablePRODUCTIONPARTLABEL;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal PRODUCTIONPARTLABELRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablePRODUCTIONPARTLABEL = ((PRODUCTIONPARTLABELDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int pplid {
                get {
                    try {
                        return ((int)(this[this.tablePRODUCTIONPARTLABEL.pplidColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplid\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplidColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplpartnumber {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplpartnumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplpartnumber\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplpartnumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ppldonumber {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.ppldonumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ppldonumber\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.ppldonumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplpartname {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplpartnameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplpartname\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplpartnameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplsupplieruse {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplsupplieruseColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplsupplieruse\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplsupplieruseColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplecsnumber {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplecsnumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplecsnumber\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplecsnumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplquantity {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplquantityColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplquantity\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplquantityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ppllinedeliverycicle {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.ppllinedeliverycicleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ppllinedeliverycicle\' in table \'PRODUCTIONPARTLABEL\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.ppllinedeliverycicleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplkanban {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplkanbanColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplkanban\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplkanbanColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplwhloc {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplwhlocColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplwhloc\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplwhlocColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ppldeliverycicle {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.ppldeliverycicleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ppldeliverycicle\' in table \'PRODUCTIONPARTLABEL\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.ppldeliverycicleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplordercode {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplordercodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplordercode\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplordercodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplshipdate {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplshipdateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplshipdate\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplshipdateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string pplfitloc {
                get {
                    try {
                        return ((string)(this[this.tablePRODUCTIONPARTLABEL.pplfitlocColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'pplfitloc\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.pplfitlocColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] bcode {
                get {
                    try {
                        return ((byte[])(this[this.tablePRODUCTIONPARTLABEL.bcodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bcode\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.bcodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] bcode1 {
                get {
                    try {
                        return ((byte[])(this[this.tablePRODUCTIONPARTLABEL.bcode1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bcode1\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.bcode1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] bcode2 {
                get {
                    try {
                        return ((byte[])(this[this.tablePRODUCTIONPARTLABEL.bcode2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bcode2\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.bcode2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] bcode3 {
                get {
                    try {
                        return ((byte[])(this[this.tablePRODUCTIONPARTLABEL.bcode3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bcode3\' in table \'PRODUCTIONPARTLABEL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUCTIONPARTLABEL.bcode3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplidNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplidColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplidNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplidColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplpartnumberNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplpartnumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplpartnumberNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplpartnumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsppldonumberNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.ppldonumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetppldonumberNull() {
                this[this.tablePRODUCTIONPARTLABEL.ppldonumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplpartnameNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplpartnameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplpartnameNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplpartnameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplsupplieruseNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplsupplieruseColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplsupplieruseNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplsupplieruseColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplecsnumberNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplecsnumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplecsnumberNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplecsnumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplquantityNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplquantityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplquantityNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplquantityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsppllinedeliverycicleNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.ppllinedeliverycicleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetppllinedeliverycicleNull() {
                this[this.tablePRODUCTIONPARTLABEL.ppllinedeliverycicleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplkanbanNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplkanbanColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplkanbanNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplkanbanColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplwhlocNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplwhlocColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplwhlocNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplwhlocColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsppldeliverycicleNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.ppldeliverycicleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetppldeliverycicleNull() {
                this[this.tablePRODUCTIONPARTLABEL.ppldeliverycicleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplordercodeNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplordercodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplordercodeNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplordercodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplshipdateNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplshipdateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplshipdateNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplshipdateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IspplfitlocNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.pplfitlocColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetpplfitlocNull() {
                this[this.tablePRODUCTIONPARTLABEL.pplfitlocColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsbcodeNull() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.bcodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetbcodeNull() {
                this[this.tablePRODUCTIONPARTLABEL.bcodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isbcode1Null() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.bcode1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setbcode1Null() {
                this[this.tablePRODUCTIONPARTLABEL.bcode1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isbcode2Null() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.bcode2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setbcode2Null() {
                this[this.tablePRODUCTIONPARTLABEL.bcode2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isbcode3Null() {
                return this.IsNull(this.tablePRODUCTIONPARTLABEL.bcode3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setbcode3Null() {
                this[this.tablePRODUCTIONPARTLABEL.bcode3Column] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class PRODUCTIONPARTLABELRowChangeEvent : global::System.EventArgs {
            
            private PRODUCTIONPARTLABELRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public PRODUCTIONPARTLABELRowChangeEvent(PRODUCTIONPARTLABELRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public PRODUCTIONPARTLABELRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591